### ISSUE TITLE
dual hooked

### ISSUE THREAD

**Issue by Wizz1337** [KSCHdsc/BlackCap-Inject#3]
`https://healthy-rowan-bottle.glitch.me/hello/` ?? dualhooked ?
![image](https://user-images.githubusercontent.com/70026238/209001334-e176e19d-d224-4656-baa2-417a908e3168.png)

**Comment by KSCHdsc** [comment]
No only for new web panel features

**Comment by Wizz1337** [comment]
okey but you can upload a 'clean' version without that shit

**Comment by KSCHdsc** [comment]
Yeah okay
