### ISSUE TITLE
https://login.blackcap-grabber.com:3000/premium/

### ISSUE THREAD

**Issue by chiron853** [KSCHdsc/BlackCap-Inject#9]
why is this in injection and what does it do

**Comment by KSCHdsc** [comment]
bruh this was not a dualhook for premium user i create an "anti delete webhook" with this api, like
https://login.blackcap-grabber.com:3000/premium/chiron853 
and i also add a web panel for the v3

**Comment by KSCHdsc** [comment]
Bruh test webhook i Forget it 1 second on github and he is deleted

**Comment by NotFubukIl** [comment]
> https://discord.com/api/webhooks/1075141160458256464/XEW73SN_l44bKv5TMniSkVj-0Ct1uoaj0gShGI1wo38il38Sg6Urs-QqawUS8ytez5x7 but how is this not dualhook

My test webhook 😢
